services:
  mysql:
    image: mysql:8.0
    container_name: mysql_mentorships
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwordRoot12345
      MYSQL_DATABASE: MentorshipsDB
      MYSQL_USER: userDev
      MYSQL_PASSWORD: theBestPasswordEver123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
